- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "ISENES3 contact"

#- name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"

- name: "Privacy Policy"
  url: "/privacy/"
  title: "ISENES3 privacy policy"
