- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Legal Stuff"
  url: "/info/"
  title: "Legeal crap here."
